package heartbeats

var alphabet = map[rune]string{
	'a': "abacate",
	'b': "banana",
	'c': "cachorro",
	'd': "dinossauro",
	'e': "elefante",
	'f': "foca",
	'g': "gato",
	'h': "hipopótamo",
	'i': "iguana",
	'j': "jabuti",
	'k': "kiwi",
	'l': "leão",
	'm': "macaco",
	'n': "navio",
	'o': "oceano",
	'p': "pato",
	'q': "queijo",
	'r': "rato",
	's': "sapo",
	't': "tigre",
	'u': "urso",
	'v': "vaca",
	'w': "waffle",
	'x': "xadrez",
	'y': "iogurte",
	'z': "zebra",
}
